### ISSUE TITLE
A small suggestion

### ISSUE THREAD

**Issue by WebShapedBiz** [fredserva/birdskitchen#4]
Hi.

Thank you for this app, it really looks nice. However, most Linux people hate, and I think that there are actually some guidelines on this, when an application is messing with their `user` folder. Please consider putting `birdskitchen` folder in the `.local` folder instead of directly in the `user` folder. 

Cheers.

**Comment by fredserva** [comment]
Don't tell me about it!
I know it's annoying to have a cluttered `user` folder.
But if you open the **Birds Kitchen** settings, you'll see that you have the possibility to move your storage folder any place you want.
Do that, then delete the initial folder.

I won't change this software behavior because the `.local` folder is an hidden one and some Linux users don't know how to access hidden files and folders.

Thanks for your feedback!

**Comment by WebShapedBiz** [comment]
Thank you for your quick reply. I did however moved my storage folder but birdskitchen kept reapearing in my User folder.

Cheers.
Siniša Perović
Webshaped Business OÜ
sinisaperovic@webshaped.biz (mailto:sinisaperovic@webshaped.biz)
+385 92 1244627 (tel:+385%2092%201244627)
https://webshaped.biz

**Comment by fredserva** [comment]
Damn! :)
That's a bug!

Never happened on my computers.
Will investigate...

**Comment by WebShapedBiz** [comment]
elementaryOS 5.1.7 (Ubuntu 18.04.4 LTS based)
Vanilla installation, nothing complied or installed without default apt-get
Linux 5.4.0-54-generic
GTK 3.22.30

Siniša Perović
Webshaped Business OÜ
sinisaperovic@webshaped.biz (mailto:sinisaperovic@webshaped.biz)
+385 92 1244627 (tel:+385%2092%201244627)
https://webshaped.biz

**Comment by fredserva** [comment]
I've installed elementary OS as a VM in VirtualBox.
Birds Kitchen keeps reapearing in the `User` folder even if you've moved the storage folder **until** you move the backup folder.
If one of the storage folders remains in the `User` folder (main storage or backup), that's a normal behavior.

**Comment by WebShapedBiz** [comment]
OK, gotcha. Thank you for your time and effort with this.

Cheers.
