### ISSUE TITLE
Alphabetical sorting is case sensitive

### ISSUE THREAD

**Issue by panthia** [fredserva/birdskitchen#7]
**Describe the bug**
CREAM will sort before Carrot

**Comment by fredserva** [comment]
That's how [`sort()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) works in Javascript.
Characters are sorted by their Unicode values.
I knew it when I developed the application, but i didn't care because I HATE WORDS WRITTEN IN CAPITAL LETTERS!
But since it seems to bother, I fixed the function so that the sorting does not take into account the lowercase and the uppercase.

It will be implemented in the next version...
